# main links
main:
  - title : "스프링"
    url : /spring/
  - title : "자바"
    url : /java/
  - title : "dbms"
    url : /dbms/
  - title : "기타 cs지식"
    url : /cs/
  - title : "포트폴리오"
    url : /about/
  - title: "카테고리 모음"
    url: /categories/
  - title: "태그 모음"
    url: /tags/
  - title: "검색"
    url: /search/

docs:
  - title: "네비게이션"
    children:
      - title: "카테고리"
        url: /categories/
      - title: "태그"
        url: /tags/
      - title: "검색"
        url: /search/

# spring sidebar
spring:
  - title: 포스팅 분류
    children:
      - title: "모두보기"
        url: /spring/
      - title: "스프링"
        url: /spring/spring-study/
      - title: "스프링-책"
        url: /spring/spring-book/
      - title: "스프링-온라인강의"
        url: /spring/spring-onlineclass/

# java sidebar
java:
  - title: 포스팅 분류
    children:
      - title: "모두보기"
        url: /java/
      - title: "자바"
        url: /java/java-study/
      - title: "자바-책"
        url: /java/java-book/
      - title: "자바-온라인강의"
        url: /java/java-onlineclass/

# dbms sidebar
dbms:
  - title: 포스팅 분류
    children:
      - title: "모두보기"
        url: /dbms/
      - title: "dbms"
        url: /dbms/dbms-study/
      - title: "mysql"
        url: /dbms/mysql/
      - title: "jpa"
        url: /dbms/jpa/

# computer-science sidebar
cs:
  - title: 포스팅 분류
    children:
      - title: "모두보기"
        url: /cs/
      - title: "기타 cs지식"
        url: /cs/cs-study/
      - title: "알고리즘"
        url: /cs/algorithm/
      - title: "자료구조"
        url: /cs/datastructures/
      - title: "네트워크"
        url: /cs/network/

# portfolio sidebar
portfolio:
  - title: "About Lala"
    url: /about/
  - title: "프로젝트 모음"
    url: /portfolio/


  # - title: "About"
  #   url: https://mmistakes.github.io/minimal-mistakes/about/
  # - title: "Sample Posts"
  #   url: /year-archive/
  # - title: "Sample Collections"
  #   url: /collection-archive/
  # - title: "Sitemap"
  #   url: /sitemap/
