# main links
main:
  - title : "스프링"
    url : /spring/
  - title : "자바"
    url : /java/
  - title : "데이터베이스"
    url : /database/
  - title : "기타 cs지식"
    url : /computer-science/
  - title : "포트폴리오"
    url : /portfolio/
  - title: "카테고리 모음"
    url: /categories/
  - title: "태그 모음"
    url: /tags/
  - title: "검색"
    url: /search/

docs:
  - title: "네비게이션"
    children:
      - title: "카테고리"
        url: /categories/
      - title: "태그"
        url: /tags/
      - title: "검색"
        url: /search/

# spring sidebar
spring:
  - title: 포스팅 분류
    children:
      - title: "스프링"
        url : /spring/
      - title: "스프링-책"
        url : /spring/book/
      - title: "스프링-온라인강의"
        url : /spring/online-study/

# java sidebar
java:
  - title: 포스팅 분류
    children:
      - title: "자바"
        url : /java/
      - title: "자바-책"
        url : /java/book/
      - title: "자바-온라인강의"
        url : /java/online-study/

# database sidebar
database:
  - title: 포스팅 분류
    children:
      - title: "DBMS"
        url : /database/
      - title: "mysql"
        url : /database/mysql/
      - title: "jpa"
        url : /database/jpa/

# computer-science sidebar
computer-science:
  - title: 포스팅 분류
    children:
      - title: "기타 cs지식"
        url : /computer-science/
      - title: "알고리즘"
        url : /computer-science/algorithm
      - title: "자료구조"
        url : /computer-science/datastructures/
      - title: "네트워크"
        url : /computer-science/network/


  # - title: "About"
  #   url: https://mmistakes.github.io/minimal-mistakes/about/
  # - title: "Sample Posts"
  #   url: /year-archive/
  # - title: "Sample Collections"
  #   url: /collection-archive/
  # - title: "Sitemap"
  #   url: /sitemap/
